#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 22 13:08:03 2017

@author: taimur
"""

def reverse_vowels(input_str):
    temp = list(input_str)
    lst = []
    count=0
    for index in range(len(input_str)):
        print(input_str[index])
        if(input_str[index] in ['a', 'e', 'i', 'o', 'u']):
            lst.append(input_str[index])
            
    print(lst)
    
    for index in range(len(input_str)-1, -1, -1):
        if(input_str[index] in ['a', 'e', 'i', 'o', 'u']):
            temp[index] = lst[count]
            count+=1
    return "".join(temp)
            
            
        
        